LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

MAX_CHANGES: 50
ANARCI_NCPU: 28
MEMORY_LIMIT: '120Gb'
TREE_DEPTH: 3
MAX_CTR_COMPLEXITY: 4
TREE_LEARNING_RATE: 0.35
LEARNING_BATCH_SIZE: 400000
TOTAL_ESTIMATORS: 1500
VERBOSE_FREQUENCY: 10
