LOGGING_LEVEL: 'DEBUG'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

MAX_CHANGES: 50
ANARCI_NCPU: 14
MEMORY_LIMIT: '100Gb'
TREE_DEPTH: 4
MAX_CTR_COMPLEXITY: 4
TREE_LEARNING_RATE: 0.35
LEARNING_BATCH_SIZE: 300000
TOTAL_ESTIMATORS: 1500
VERBOSE_FREQUENCY: 10
